version: '3.3'
services:
    db:
      platform: linux/x86_64
      image: mysql:8.0
      container_name: rew_mysql
      ports:
        - "3306:3306"
      volumes:
        - /home/ubuntu/wrk/docker/mysqld/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_DATA=${MYSQL_DATA}

