
##############################################################################################
###> New Dockerfile  -> Richard Eric Walts as eric ---> 2023-06-24_15:16:37 init <<<
##############################################################################################
# syntax=docker/dockerfile:1
FROM 683853257660.dkr.ecr.us-west-2.amazonaws.com/rewbin:latest 
WORKDIR /home/ubuntu/docker/
# install app dependencies
RUN apt-get update
RUN apt-get install -y apt-utils expect

# variables for mysql install

# mount data volume

# install app




# start the app
#RUN /usr/sbin/mysqld start
# final configuration


EXPOSE 80
