
############################################################################################
###> ,,, New Dockerfile .. created by Richard Eric Walts .. eric --> 2023-10-19_20:08:08 ,,,
############################################################################################

# syntax=docker/dockerfile:1

FROM nginx:latest

WORKDIR /var/www/html

COPY ./default.conf /etc/nginx/conf.d/default.conf


