###> This is the second file. 
###> Does not recreate nginx, only modifies it.

---
services:
  nginx:
    build: ./nginx/
    container_name: nginxphp-nginx-1
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./www/html/:/var/www/html/

  php:
    image: php:8.1-fpm
    container_name: php-container2
    expose:
      - 9000
    volumes:
      - ./www/html/:/var/www/html/ 

